version: 0.2

phases:
  build:
    commands:
      # Replace the placeholder in ecs-task-definition.json with the actual ECR repository URI
      - sed -i "s|REPOSITORY_URI_PLACEHOLDER|${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION}|g" ecs-task-definition.json
      # Create imagedefinitions.json file with the updated image URI
      - echo '[{"name":"iris-container","image":"'${AWS_ACCOUNT_ID}'.dkr.ecr.'${AWS_REGION}'.amazonaws.com/'${ECR_REPO_NAME}':'${CODEBUILD_RESOLVED_SOURCE_VERSION}'","cpu":256,"memory":512,"essential":true,"portMappings":[{"containerPort":80,"hostPort":80}],"logConfiguration":{"logDriver":"awslogs","options":{"awslogs-group":"/ecs/iris-logs","awslogs-region":"your-region","awslogs-stream-prefix":"iris-container"}},"networkMode":"awsvpc","requiresCompatibilities":["FARGATE"]}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
